# Generated by Django 4.1.4 on 2022-12-11 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('user_name', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('tags', models.CharField(max_length=50)),
                ('url_repo', models.CharField(max_length=150)),
                ('idusuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miportafolio.usuario')),
            ],
        ),
    ]
