# Generated by Django 4.1.4 on 2022-12-11 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miportafolio', '0002_alter_usuario_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='proyecto',
            table='proyecto',
        ),
    ]
